spring:
  application:
    name: Cloud_Config_Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MohammedImranShaik/Configuration_Properties
server:
  port: 9093
